# vim: set ts=2 sw=2 et ai foldmethod=indent:
#
# See http://ci.openstack.org/zuul/zuul.html#configuration
#

pipelines:

  # Pipeline doing prechecks such as syntax linting
  # Does NOT report back to Gerrit.
  - name: check-silent
    manager: IndependentPipelineManager
    trigger:
      - event: patchset-created
      - event: comment-added
        comment_filter: (?i)^\s*recheck\.?\s*$

  # Pipeline doing prechecks such as syntax linting
  # Being run on any patchset and WILL REPORT verified +1/-1
  - name: check
    manager: IndependentPipelineManager
    trigger:
      - event: patchset-created
      - event: comment-added
        comment_filter: (?i)^\s*recheck\.?\s*$
    success:
      # Prevents people from being able to submit a change
      # before unit tests have been run.
      verified: 0
    failure:
      verified: -1

  # Pipeline that only get run when someone trusted has reviewed the code
  # (cr +2). Should be used to run tests and will report verified +2/-2.
  - name: gate
    manager: IndependentPipelineManager
    trigger:
      - event: comment-added
        approval:
          - code-review: 2
# Silented for production deployment
#    success:
#      verified: 1
#      code-review: 1
#      # Let Zuul merge the change \O/
#      # Disabled until ready
#      #submit: true
#    failure:
#      verified: -1
#      # We really want to block submission when tests fails
#      code-review: -2

  - name: postmerge
    manager: IndependentPipelineManager
    trigger:
      - event: change-merged
# Silented for production deployment
#    success:
#      code-review: 0
#      verified: 0
#      force-message: True
#    failure:
#      code-review: 0
#      verified: 0
#      force-message: True

# Fine tune some jobs
jobs:
  - name: ^.*merge$
    failure-message: Change could not be automatically merged. Please rebase it and reupload.
  - name: mediawiki-core-master-phpunit-all
    branch: ^master$
    success-message: Change looked fine once merged.
    failure-message: ERROR! It seems this job introduced a regression although it might be caused by a previous commit.

projects:
  - name: mediawiki/core
    check-silent:
      - mediawiki-core-merge:
        - mediawiki-core-lint
    gate:
      - mediawiki-core-merge:
        - mediawiki-core-lint:
          - mediawiki-core-phpunit-databaseless:
            - mediawiki-core-install-sqlite:
              - mediawiki-core-phpunit-api
              - mediawiki-core-phpunit-misc
              - mediawiki-core-phpunit-parser
    postmerge:
      - mediawiki-core-lint
      - mediawiki-core-master-phpunit-all

  - name: operations/puppet
    check-silent:
      - operations-puppet-validate
    gate:
      - operations-puppet-validate
    # No postmerge needed yet

#### MediaWiki extensions #############################################

  - name: mediawiki/extensions/DataValues
    check-silent:
      - mwext-DataValues-merge:
        - mwext-DataValues-lint
    gate:
      - mwext-DataValues-merge:
        - mwext-DataValues-lint:
          - mwext-DataValues-install:
            - mwext-DataValues-testextensions

  - name: mediawiki/extensions/Diff
    check-silent:
      - mwext-Diff-merge:
        - mwext-Diff-lint
    gate:
      - mwext-Diff-merge:
        - mwext-Diff-lint:
          - mwext-Diff-install:
            - mwext-Diff-testextensions

  - name: mediawiki/extensions/LabeledSectionTransclusion
    check-silent:
      - mwext-LabeledSectionTransclusion-merge:
        - mwext-LabeledSectionTransclusion-lint
    gate:
      - mwext-LabeledSectionTransclusion-merge:
        - mwext-LabeledSectionTransclusion-lint:
          - mwext-LabeledSectionTransclusion-install:
            - mwext-LabeledSectionTransclusion-testextensions

  - name: mediawiki/extensions/MobileFrontend
    check-silent:
      - mwext-MobileFrontend-merge:
        - mwext-MobileFrontend-lint
    gate:
      - mwext-MobileFrontend-merge:
        - mwext-MobileFrontend-lint:
          - mwext-MobileFrontend-install:
            - mwext-MobileFrontend-testextensions

  - name: mediawiki/extensions/TitleBlacklist
    check-silent:
      - mwext-TitleBlacklist-merge:
        - mwext-TitleBlacklist-lint
    gate:
      - mwext-TitleBlacklist-merge:
        - mwext-TitleBlacklist-lint:
          - mwext-TitleBlacklist-install:
            - mwext-TitleBlacklist-testextensions

  - name: mediawiki/extensions/Translate
    check-silent:
      - mwext-Translate-merge:
        - mwext-Translate-lint
    gate:
      - mwext-Translate-merge:
        - mwext-Translate-lint:
          - mwext-Translate-install:
            - mwext-Translate-testextensions

  - name: mediawiki/extensions/TranslationNotifications
    check-silent:
      - mwext-TranslationNotifications-merge:
        - mwext-TranslationNotifications-lint
    gate:
      - mwext-TranslationNotifications-merge:
        - mwext-TranslationNotifications-lint:
          - mwext-TranslationNotifications-install:
            - mwext-TranslationNotifications-testextensions

  - name: mediawiki/extensions/UniversalLanguageSelector
    check-silent:
      - mwext-UniversalLanguageSelector-merge:
        - mwext-UniversalLanguageSelector-lint
    gate:
      - mwext-UniversalLanguageSelector-merge:
        - mwext-UniversalLanguageSelector-lint:
          - mwext-UniversalLanguageSelector-install:
            - mwext-UniversalLanguageSelector-testextensions

  - name: mediawiki/extensions/Validator
    check-silent:
      - mwext-Validator-merge:
        - mwext-Validator-lint
    gate:
      - mwext-Validator-merge:
        - mwext-Validator-lint:
          - mwext-Validator-install:
            - mwext-Validator-testextensions

