# vim: set ts=2 sw=2 et ai foldmethod=indent:
#
# See http://ci.openstack.org/zuul/zuul.html#configuration
#

pipelines:

  # Pipeline doing prechecks such as syntax linting
  # Does NOT report back to Gerrit.
  - name: check-silent
    manager: IndependentPipelineManager
    trigger:
      - event: patchset-created
      - event: comment-added
        comment_filter: (?i)^\s*recheck\.?\s*$

  # Pipeline doing prechecks such as syntax linting
  # Being run on any patchset and WILL REPORT verified +1/-1
  - name: check
    manager: IndependentPipelineManager
    trigger:
      - event: patchset-created
      - event: comment-added
        comment_filter: (?i)^\s*recheck\.?\s*$
    success:
      verified: 1
    failure:
      verified: -1

  # Pipeline that only get run when someone trusted has reviewed the code
  # (cr +2). Should be used to run tests and will report verified +2/-2.
  - name: gate
    manager: IndependentPipelineManager
    trigger:
      - event: comment-added
        approval:
          - code-review: 2
# Silented for production deployment
#    success:
#      verified: 1
#      code-review: 1
#      # Let Zuul merge the change \O/
#      # Disabled until ready
#      #submit: true
#    failure:
#      verified: -1
#      # We really want to block submission when tests fails
#      code-review: -2

  - name: postmerge
    manager: IndependentPipelineManager
    trigger:
      - event: change-merged
# Silented for production deployment
#    success:
#      code-review: 0
#      verified: 0
#      force-message: True
#    failure:
#      code-review: 0
#      verified: 0
#      force-message: True

# Fine tune some jobs
jobs:
  - name: ^.*merge$
    failure-message: Change could not be automatically merged. Please rebase it and reupload.
  - name: mediawiki-core-master-phpunit-all
    branch: ^master$
    success-message: Change looked fine once merged.
    failure-message: ERROR! It seems this job introduced a regression although it might be caused by a previous commit.

projects:
  - name: mediawiki/core
    check-silent:
      - mediawiki-core-merge:
        - mediawiki-core-lint
    gate:
      - mediawiki-core-merge:
        - mediawiki-core-lint:
          - mediawiki-core-phpunit-databaseless:
            - mediawiki-core-install-sqlite:
              - mediawiki-core-phpunit-api
              - mediawiki-core-phpunit-misc
              - mediawiki-core-phpunit-parser
    postmerge:
      - mediawiki-core-lint
      - mediawiki-core-master-phpunit-all

  - name: operations/puppet
    check:
      - operations-puppet-validate
    gate:
      - operations-puppet-validate

    # No postmerge needed yet
