# vim: set ts=2 sw=2 et ai foldmethod=indent:
#
# See http://ci.openstack.org/zuul/zuul.html#configuration
#

pipelines:

  # Pipeline doing prechecks such as syntax linting
  # Does NOT report back to Gerrit.
  - name: check-silent
    manager: IndependentPipelineManager
    trigger:
      - event: patchset-created
      - event: comment-added
        comment_filter: (?i)^\s*recheck\.?\s*$

  # Pipeline doing prechecks such as syntax linting
  # Being run on any patchset.
  - name: check
    manager: IndependentPipelineManager
    trigger:
      - event: patchset-created
      - event: comment-added
        comment_filter: (?i)^\s*recheck\.?\s*$
    success:
      # Prevents people from being able to submit a change
      # before unit tests have been run.
      verified: 0
      # Give a hint that we have more or less looked at the code,
      # also clear out a potential previous vote
      code-review: 1
    failure:
      verified: -1
      # Remove the flag that says we looked at it
      code-review: 0

  # Voting check for project that lack unit tests and only rely
  # on lint check. Similiar to 'check' but additionally vote V+1
  # This is mostly for operations/puppet which ask to get V+1 whenever
  # change is linted since they dont have unit tests.
  - name: check-voter
    manager: IndependentPipelineManager
    trigger:
      - event: patchset-created
      - event: comment-added
        comment_filter: (?i)^\s*recheck\.?\s*$
    success:
      verified: 1
      code-review: 1
    failure:
      verified: -1
      code-review: 0

  # Pipelines that only get run when someone trusted has reviewed the code
  # (cr +2). Should be used to run tests and will report verified +2/-2.
  #
  # Silent gate (does not report anything back to Gerrit):
  - name: gate-silent
    manager: IndependentPipelineManager
    trigger:
      - event: comment-added
        approval:
          - code-review: 2

  # Actual gate (report/vote in Gerrit)
  #
  # WARNING: do modify the gate-and-submit pipeline below whenever
  #          changing the gate pipeline.
  #
  - name: gate
    manager: IndependentPipelineManager
    trigger:
      - event: comment-added
        approval:
          - code-review: 2
    success:
      verified: 1
      code-review: 1
      # Let Zuul merge the change \O/
      # Disabled until ready
      #submit: true
    failure:
      verified: -1
      # We really want to block submission when tests fails
      code-review: -2

  # Actual gate (report/vote in Gerrit)
  # Will auto submit change on success!!!!!!!!
  #
  # WARNING: do modify the gate pipeline below whenever changing
  #          the gate-and-submit pipeline.
  #
  - name: gate-and-submit
    manager: IndependentPipelineManager
    trigger:
      - event: comment-added
        approval:
          - code-review: 2
    success:
      verified: 1
      code-review: 1
      # Let Zuul merge the change \O/
      submit: true
    failure:
      verified: -1
      # We really want to block submission when tests fails
      code-review: -2

  - name: postmerge
    manager: IndependentPipelineManager
    trigger:
      - event: change-merged
# Silented for production deployment
#    success:
#      code-review: 0
#      verified: 0
#      force-message: True
#    failure:
#      code-review: 0
#      verified: 0
#      force-message: True

# Fine tune some jobs
jobs:
  - name: ^.*merge$
    failure-message: Change could not be automatically merged. Please rebase it and reupload.

  # JSLint
  #
  # Disabled by default since most MediaWiki extensions do not pass tests yet:
  - name: ^.*-jslint$
    voting: false  # Until we are sure it works fine
  # Explicitly enable voting for extensions we know are passing JSHint:
  - name: mwext-VisualEditor-jslint
    voting: true

  # Various failing jobs that need to be fixed eventually

  # Echo installer does not support SQLite backend :-/
  - name: mwext-Echo-install
    voting: false
  - name: mwext-Echo-testextensions
    voting: false

  # GeoMathTest::testRectWrapAround() fails as of Dec 5th 2012
  - name: mwext-GeoData-testextensions
    voting: false

  - name: mediawiki-core-master-phpunit-all
    branch: ^master$
    success-message: Change looked fine once merged.
    failure-message: ERROR! It seems this job introduced a regression although it might be caused by a previous commit.

  # MediaWiki Core regression tests (on merge and per branches):
  - name: ^mediawiki-core-regression-.*
    failure-message: ERROR! It seems this job introduced a regression although it might be caused by a previous commit.
  - name: mediawiki-core-regression-master
    branch: ^master$
  - name: mediawiki-core-regression-REL1_19
    branch: ^REL1_19$
  - name: mediawiki-core-regression-REL1_20
    branch: ^REL1_20$
  # Extensions for which tests are non functional or absents:
  - name: mwext-EtherEditor-testextensions
    voting: false
  - name: mwext-cldr-testextensions
    voting: false
  - name: mwext-TranslationNotifications-testextensions
    voting: false

projects:
  - name: mediawiki/core
    check:
      - mediawiki-core-merge:
        - mediawiki-core-lint
    gate-and-submit:
      - mediawiki-core-merge:
        - mediawiki-core-lint:
          - mediawiki-core-phpunit-databaseless:
            - mediawiki-core-install-sqlite:
              - mediawiki-core-phpunit-api
              - mediawiki-core-phpunit-misc
              - mediawiki-core-phpunit-parser
    postmerge:
      - mediawiki-core-lint
      - mediawiki-core-master-phpunit-all
      - mediawiki-core-regression-master
      - mediawiki-core-regression-REL1_19
      - mediawiki-core-regression-REL1_20

  - name: analytics/libanon
    gate-and-submit:
     - analytics-libanon

  - name: analytics/udp-filters
    gate-and-submit:
     - analytics-udp-filters

  - name: operations/mediawiki-config
    check:
      - operations-mw-config-phplint:
        - operations-mw-config-tests
    gate:
      - operations-mw-config-phplint:
        - operations-mw-config-tests

  - name: operations/puppet
    # Only lint on submission for now, that will be voting
    check-voter:
      - operations-puppet-validate

  - name: translatewiki
    check:
      - translatewiki-phplint
      - translatewiki-puppet-validate
      - translatewiki-shelllint
    gate:
      - translatewiki-phplint
      - translatewiki-puppet-validate
      - translatewiki-shelllint

  - name: wikimedia/bugzilla/wikibugs
    # Only lint on submission for now, that will be voting
    check-voter:
      - wikimedia-bugzilla-wikibugs-perllint

#### MediaWiki extensions #############################################

  - name: mediawiki/extensions/cldr
    check:
      - mwext-cldr-merge:
        - mwext-cldr-jslint
        - mwext-cldr-lint
    gate:
      - mwext-cldr-merge:
        - mwext-cldr-jslint
        - mwext-cldr-lint:
          - mwext-cldr-install:
            - mwext-cldr-testextensions

  - name: mediawiki/extensions/DataValues
    check:
      - mwext-DataValues-merge:
#        - mwext-DataValues-jslint
        - mwext-DataValues-lint
    gate:
      - mwext-DataValues-merge:
#        - mwext-DataValues-jslint
        - mwext-DataValues-lint:
          - mwext-DataValues-install:
            - mwext-DataValues-testextensions

  - name: mediawiki/extensions/EtherEditor
    check:
      - mwext-EtherEditor-merge:
#        - mwext-EtherEditor-jslint
        - mwext-EtherEditor-lint
    gate:
      - mwext-EtherEditor-merge:
        - mwext-EtherEditor-lint:
#        - mwext-EtherEditor-jslint
          - mwext-EtherEditor-install:
            - mwext-EtherEditor-testextensions

  - name: mediawiki/extensions/Diff
    check:
      - mwext-Diff-merge:
        - mwext-Diff-jslint
        - mwext-Diff-lint
    gate:
      - mwext-Diff-merge:
        - mwext-Diff-jslint
        - mwext-Diff-lint:
          - mwext-Diff-install:
            - mwext-Diff-testextensions

  - name: mediawiki/extensions/Echo
    check:
      - mwext-Echo-merge:
        - mwext-Echo-jslint
        - mwext-Echo-lint
    gate:
      - mwext-Echo-merge:
        - mwext-Echo-jslint
        - mwext-Echo-lint:
          - mwext-Echo-install:
            - mwext-Echo-testextensions

  - name: mediawiki/extensions/EventLogging
    check:
      - mwext-EventLogging-merge:
        - mwext-EventLogging-jslint
        - mwext-EventLogging-lint
    gate:
      - mwext-EventLogging-merge:
        - mwext-EventLogging-jslint
        - mwext-EventLogging-lint:
          - mwext-EventLogging-install:
            - mwext-EventLogging-testextensions

  - name: mediawiki/extensions/GeoData
    check:
      - mwext-GeoData-merge:
        - mwext-GeoData-jslint
        - mwext-GeoData-lint
    gate:
      - mwext-GeoData-merge:
        - mwext-GeoData-jslint
        - mwext-GeoData-lint:
          - mwext-GeoData-install:
            - mwext-GeoData-testextensions

  - name: mediawiki/extensions/LabeledSectionTransclusion
    check:
      - mwext-LabeledSectionTransclusion-merge:
        - mwext-LabeledSectionTransclusion-jslint
        - mwext-LabeledSectionTransclusion-lint
    gate-silent:
      - mwext-LabeledSectionTransclusion-merge:
        - mwext-LabeledSectionTransclusion-jslint
        - mwext-LabeledSectionTransclusion-lint:
          - mwext-LabeledSectionTransclusion-install:
            - mwext-LabeledSectionTransclusion-testextensions

  - name: mediawiki/extensions/LiquidThreads
    check:
      - mwext-LiquidThreads-merge:
        - mwext-LiquidThreads-jslint
        - mwext-LiquidThreads-lint
    gate:
      - mwext-LiquidThreads-merge:
        - mwext-LiquidThreads-jslint
        - mwext-LiquidThreads-lint
# No unit tests for now :(

  - name: mediawiki/extensions/MobileFrontend
    check:
      - mwext-MobileFrontend-merge:
        - mwext-MobileFrontend-lint
        - mwext-MobileFrontend-jslint
    gate:
      - mwext-MobileFrontend-merge:
        - mwext-MobileFrontend-jslint
        - mwext-MobileFrontend-lint:
          - mwext-MobileFrontend-install:
            - mwext-MobileFrontend-testextensions

  - name: mediawiki/extensions/OpenStackManager
    check:
      - mwext-OpenStackManager-merge:
        - mwext-OpenStackManager-lint
        - mwext-OpenStackManager-jslint
    gate:
      - mwext-OpenStackManager-merge:
        - mwext-OpenStackManager-jslint
        - mwext-OpenStackManager-lint:
          - mwext-OpenStackManager-install
# No unit tests for now :(
#          - mwext-OpenStackManager-install:
#            - mwext-OpenStackManager-testextensions

  - name: mediawiki/extensions/ParserFunctions
    check:
      - mwext-ParserFunctions-merge:
        - mwext-ParserFunctions-jslint
        - mwext-ParserFunctions-lint
    gate:
      - mwext-ParserFunctions-merge:
        - mwext-ParserFunctions-jslint
        - mwext-ParserFunctions-lint:
          - mwext-ParserFunctions-install:
            - mwext-ParserFunctions-testextensions

  # Parsoid is mostly JavaScript so we just run jsHint (and merge of course)
  - name: mediawiki/extensions/Parsoid
    check:
      - mwext-Parsoid-merge:
        - mwext-Parsoid-jslint
    gate:
      - mwext-Parsoid-merge:
        - mwext-Parsoid-jslint

  - name: mediawiki/extensions/Renameuser
    check:
      - mwext-Renameuser-merge:
        - mwext-Renameuser-lint
        - mwext-Renameuser-jslint
    gate:
      - mwext-Renameuser-merge:
        - mwext-Renameuser-jslint
        - mwext-Renameuser-lint:
          - mwext-Renameuser-install
# No Unit tests yet :(
#          - mwext-Renameuser-install:
#            - mwext-Renameuser-testextensions

  - name: mediawiki/extensions/Score
    check:
      - mwext-Score-merge:
        - mwext-Score-lint
        - mwext-Score-jslint
    gate:
      - mwext-Score-merge:
        - mwext-Score-jslint
        - mwext-Score-lint:
          - mwext-Score-install
# No Unit tests yet :(
#          - mwext-Score-install:
#            - mwext-Score-testextensions

  - name: mediawiki/extensions/SVGEdit
    check:
      - mwext-SVGEdit-merge:
        - mwext-SVGEdit-jslint
        - mwext-SVGEdit-lint
    gate:
      - mwext-SVGEdit-merge:
        - mwext-SVGEdit-jslint
        - mwext-SVGEdit-lint:
          - mwext-SVGEdit-install
# No PHPUnit tests for now so simply disable triggering them
# If you want to enable PHPUnit tests, delete the line above
# and uncomment the two lines below:
#          - mwext-SVGEdit-install:
#            - mwext-SVGEdit-testextensions

  - name: mediawiki/extensions/TimedMediaHandler
    check:
      - mwext-TimedMediaHandler-merge:
        - mwext-TimedMediaHandler-jslint
        - mwext-TimedMediaHandler-lint
    gate:
      - mwext-TimedMediaHandler-merge:
        - mwext-TimedMediaHandler-jslint
        - mwext-TimedMediaHandler-lint
# Requires the MwEmbedSupport extension :(
#        - mwext-TimedMediaHandler-lint:
#          - mwext-TimedMediaHandler-install:
#            - mwext-TimedMediaHandler-testextensions

  - name: mediawiki/extensions/TitleBlacklist
    check:
      - mwext-TitleBlacklist-merge:
        - mwext-TitleBlacklist-jslint
        - mwext-TitleBlacklist-lint
    gate:
      - mwext-TitleBlacklist-merge:
        - mwext-TitleBlacklist-jslint
        - mwext-TitleBlacklist-lint:
          - mwext-TitleBlacklist-install:
            - mwext-TitleBlacklist-testextensions

  - name: mediawiki/extensions/Translate
    check:
      - mwext-Translate-merge:
#        - mwext-Translate-jslint
        - mwext-Translate-lint
    gate-and-submit:
      - mwext-Translate-merge:
#        - mwext-Translate-jslint
        - mwext-Translate-lint:
          - mwext-Translate-install:
            - mwext-Translate-testextensions

  - name: mediawiki/extensions/TranslationNotifications
    check:
      - mwext-TranslationNotifications-merge:
        - mwext-TranslationNotifications-jslint
        - mwext-TranslationNotifications-lint
    gate:
      - mwext-TranslationNotifications-merge:
        - mwext-TranslationNotifications-jslint
        - mwext-TranslationNotifications-lint:
          - mwext-TranslationNotifications-install:
            - mwext-TranslationNotifications-testextensions

  - name: mediawiki/extensions/UniversalLanguageSelector
    check:
      - mwext-UniversalLanguageSelector-merge:
#        - mwext-UniversalLanguageSelector-jslint
        - mwext-UniversalLanguageSelector-lint
    gate:
      - mwext-UniversalLanguageSelector-merge:
#        - mwext-UniversalLanguageSelector-jslint
        - mwext-UniversalLanguageSelector-lint:
          - mwext-UniversalLanguageSelector-install:
            - mwext-UniversalLanguageSelector-testextensions

  - name: mediawiki/extensions/Validator
    check:
      - mwext-Validator-merge:
        - mwext-Validator-jslint
        - mwext-Validator-lint
    gate:
      - mwext-Validator-merge:
        - mwext-Validator-jslint
        - mwext-Validator-lint:
          - mwext-Validator-install:
            - mwext-Validator-testextensions

  - name: mediawiki/extensions/VisualEditor
    check:
      - mwext-VisualEditor-merge:
        - mwext-VisualEditor-jslint
        - mwext-VisualEditor-lint
    gate-and-submit:
      - mwext-VisualEditor-merge:
        - mwext-VisualEditor-jslint
        - mwext-VisualEditor-lint:
          - mwext-VisualEditor-install
# No PHPUnit tests for now so simply disable triggering them
# If you want to enable PHPUnit tests, delete the line above
# and uncomment the two lines below:
#          - mwext-VisualEditor-install:
#            - mwext-VisualEditor-testextensions

  - name: mediawiki/extensions/Wikibase
    check-silent:
      - mwext-Wikibase-merge:
        - mwext-Wikibase-jslint
        - mwext-Wikibase-lint
    gate-silent:
      - mwext-Wikibase-merge:
        - mwext-Wikibase-jslint
        - mwext-Wikibase-lint:
          - mwext-Wikibase-install:
            - mwext-Wikibase-testextensions
