- job-template:
    name: 'operations-mw-config-tests'
    defaults: use-remote-zuul
    triggers:
     - zuul
    builders:
     - shell: 'phpunit --log-junit logs/junit.xml'
    publishers:
     - phpunit-junit

- project:
    name: 'operations-mw-config'

    jobs:
     - '{name}-phplint'
     - operations-mw-config-tests
