- job-template:
    name: 'operations-mw-config-tests'
    defaults: use-zuul
    triggers:
     - zuul
    builders:
     - shell: 'phpunit --log-junit logs/junit.xml'
    publishers:
     - xunit:
        types:
         - phpunit:
            pattern: 'logs/junit.xml'

- project:
    name: 'operations-mw-config'
    gerrit-name: 'operations/mediawiki-config'
    jobs:
     - '{name}-phplint'
     - operations-mw-config-tests
